FAB_XPATH = "//android.widget.ImageButton[@resource-id='it.feio.android.omninotes.alpha:id/fab_expand_menu_button']"
TN_tooltip_XPATH = "//android.widget.TextView[@text='Text note']"
TN_Button_XPATH = "//android.widget.ImageButton[@resource-id='it.feio.android.omninotes.alpha:id/fab_note']"
TN_Title_ID = "it.feio.android.omninotes.alpha:id/detail_title"
TN_Body_ID = "it.feio.android.omninotes.alpha:id/detail_content"
TN_Back_XPATH = "//android.widget.ImageButton[@content-desc='drawer open']"
drawer_title_ID = "it.feio.android.omninotes.alpha:id/note_title"
drawer_body_ID = "it.feio.android.omninotes.alpha:id/note_content"